name: Deploy to Packagist

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' 
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run lint
        run: composer lint
          
      
      - name: Run tests
        run: composer test

      - name: Trigger Packagist update
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $PACKAGIST_TOKEN" \
            https://packagist.org/api/update-package?username=josephdelassalle&package=php_scrapyd_package
